### ISSUE TITLE
Unable to finish example from usage.md

### ISSUE THREAD

**Issue by JonasToth** [Ericsson/CodeCompass#142]
Hello everybody,

I installed CodeCompass successfully on my server, now i want to use it for my projects. Here is the structure:

```
(cc)jonas@homeserver:~/cc$ ls -1
CodeCompass
CodeCompass-deps
CodeCompass-install
database
projects
workdir
```

To get started I tried the example from usage.md, tinyxml2.
I followed the instructions and it kinda worked, but starting the webserver does not finish cleanly.

```
/home/jonas/cc/CodeCompass-install/bin/CodeCompass_parser -d "pgsql:database=cc_db;port=10500" --data-dir /home/jonas/cc/workdir/tinyxml2/data -i /home/jonas/cc/projects/tinyxml2/build/compile_commands.json -j4
[INFO] [searchparser] started!
[INFO] Search parse path: /home/jonas/cc/projects/tinyxml2/build/compile_commands.json
[INFORMATION] Indexer started! Mode: CREATE
[WARNUNG] Failed to write out database to /home/jonas/cc/workdir/tinyxml2/data/search/suggest/filename/suggest.db. It's normal if the database is empty.
[INFORMATION] Indexed 1 file(s)
[INFORMATION] Modified 0 file(s)
[INFORMATION] Indexer finished!
[INFO] [metricsparser] started!
[INFO] Metrics parse path: /home/jonas/cc/projects/tinyxml2/build/compile_commands.json
[INFO] Count metrics for /home/jonas/cc/projects/tinyxml2/build/compile_commands.json
[INFO] [gitparser] started!
[INFO] Git parse path: /home/jonas/cc/projects/tinyxml2/build/compile_commands.json
[INFO] [dummyparser] started!
[INFO] [cppparser] started!
[INFO] (2/2) Parsing /home/jonas/cc/projects/tinyxml2/xmltest.cpp
[INFO] (1/2) Parsing /home/jonas/cc/projects/tinyxml2/tinyxml2.cpp
warning: optimization flag '-fno-devirtualize' is not supported
warning: optimization flag '-fno-devirtualize' is not supported
```

The warning seems to be related to the failure of the webserver, but see yourself:

```
(cc)jonas@homeserver:~/cc$ ./CodeCompass-install/bin/CodeCompass_webserver -w /home/jonas/cc/workdir/ -p 10499 -d "pgsql:host=localhost;database=cc_db;port=10500"
[INFO] Workspace
  id = tinyxml2
  connection = pgsql:host=localhost;database=cc_db;port=10500
  datadir = /home/jonas/cc/workdir/tinyxml2/data/
  description = tinyxml2 project

[INFO] Mongoose web server starting on port 10499
[INFORMATION] Search server started!
[SCHWERWIEGEND] Failed to load the file name suggestion database!
java.io.EOFException
	at org.apache.lucene.store.InputStreamDataInput.readByte(InputStreamDataInput.java:37)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:96)
	at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:134)
	at org.apache.lucene.util.fst.FST.<init>(FST.java:322)
	at org.apache.lucene.util.fst.FST.<init>(FST.java:308)
	at org.apache.lucene.search.suggest.analyzing.AnalyzingSuggester.load(AnalyzingSuggester.java:593)
	at cc.search.suggestion.SuggestionHandler.loadFileNameSuggester(SuggestionHandler.java:120)
	at cc.search.suggestion.SuggestionHandler.loadDatabases(SuggestionHandler.java:47)
	at cc.search.service.app.service.SearchHandler.<init>(SearchHandler.java:156)
	at cc.search.service.app.service.ServiceApp.<init>(ServiceApp.java:30)
	at cc.search.service.app.service.ServiceApp.main(ServiceApp.java:51)

[INFORMATION] Start serving search for index /home/jonas/cc/workdir/tinyxml2/data//search
```

If I try to connect, there is a white page, but the source code tells me that CodeCompass is working, the icon is sent as well. But no content, just a blank page.

Could you help me out with that? What is the problem and how can I fix it?

**Comment by whisperity** [comment]
First, open the developer console in the browser (`Ctrl`-`Shift`-`Q` in Firefox) and see the `Console`, then do a full reload (`Ctrl`-`F5`) of the page. The exception in the webserver is not a "real" problem which _should_ break the usability of the application, I get that error every day (mostly because I always skip the search database creation...)

**Comment by JonasToth** [comment]
Thank you for the response :)

Querying the console gives me the following (explaining the blank screen)

```
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/lib/codemirror.css [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/dialog/dialog.css [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/fold/foldgutter.css [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/dojo/resources/dojo.css [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/dijit/themes/claro/claro.css [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/dojox/layout/resources/ResizeHandle.css [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/dojox/image/resources/Lightbox.css [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/dojox/grid/resources/claroGrid.css [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jquery.fancytree/dist/skin-win7/ui.fancytree.min.css [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/thrift/lib/js/src/thrift.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/lib/codemirror.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/clike/clike.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/erlang/erlang.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/javascript/javascript.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/perl/perl.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/python/python.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/ruby/ruby.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/sql/sql.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/diff/diff.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/dialog/dialog.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/search/search.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/search/searchcursor.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/edit/matchbrackets.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/fold/foldcode.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/fold/foldgutter.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/fold/brace-fold.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/fold/xml-fold.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jquery/dist/jquery.min.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jsplumb/dist/js/jsPlumb-2.2.1-min.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/svg-pan-zoom/dist/svg-pan-zoom.min.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/marked/lib/marked.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/d3/d3.min.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jquery.fancytree/lib/jquery-ui.custom.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jquery.fancytree/dist/jquery.fancytree-all.min.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jquery.fancytree/dist/src/jquery.fancytree.table.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/dojo/dojo.js [HTTP/1.1 404 Not Found 0ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/lib/codemirror.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/clike/clike.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/erlang/erlang.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/javascript/javascript.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/perl/perl.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/python/python.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/ruby/ruby.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/sql/sql.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/mode/diff/diff.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/dialog/dialog.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/search/search.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/search/searchcursor.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/edit/matchbrackets.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/fold/foldcode.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/fold/foldgutter.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/codemirror/addon/fold/xml-fold.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jquery/dist/jquery.min.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jsplumb/dist/js/jsPlumb-2.2.1-min.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/svg-pan-zoom/dist/svg-pan-zoom.min.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/marked/lib/marked.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jquery.fancytree/lib/jquery-ui.custom.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jquery.fancytree/dist/jquery.fancytree-all.min.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/jquery.fancytree/dist/src/jquery.fancytree.table.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://homeserver.local:10499/scripts/node_modules/dojo/dojo.js [HTTP/1.1 404 Not Found 1ms]
ReferenceError: require is not defined[Weitere Informationen]  homeserver.local:10499:82:7
```

I searched around in the CodeCompass-install/share directory. There seem to be javascript files and so on, but i could not find the mentioned subdirectories. 
Did i miss a dependency or something like that? What information would you need?

**Comment by whisperity** [comment]
Oh... right. 🤦‍ When you install CodeCompass, `npm` is used to set up some JS modules. **But** if you are sourced into the environment, `npm` will crash, because the NPM on your system (`/usr/bin/npm`) requires a newer standard library than installed via CodeCompass. (Issue #112 &ndash; you can even scroll up in the output of `make install` and you'll see `npm` saying something like _version GLIBCXX x.y.z not found_.)

Solution is this:
 * Create an entirely new terminal and do **NOT** source the environment.
 * Nagivate into the `build` directory
 * `make install`

This way the libraries that will be used is your system's, and thus NPM won't fail and set up the modules like _jquery_ and _codemirror_ accordingly.

**Comment by JonasToth** [comment]
It worked!
Thank you very much Sir!

**Comment by whisperity** [comment]
🙂 Happy to help, and thank you, for using CodeCompass. The issue will eventually be fixed. Needless to say I've run into these already, hence the 🤦‍.
