### ISSUE TITLE
Error message at start if search parsing didn't happen should be more graceful

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#259]
If a project is parsed without giving a folder as input but the search parser is enabled, no search parsing will be done. If at server start the user has the search service module loaded, the following ungraceful and frightening error is printed:

```
[SEVERE] Failed to load the file name suggestion database!
java.io.EOFException
    at org.apache.lucene.store.InputStreamDataInput.readByte(InputStreamDataInput.java:37)
    at org.apache.lucene.store.DataInput.readInt(DataInput.java:96)
    at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:134)
    at org.apache.lucene.util.fst.FST.<init>(FST.java:322)
    at org.apache.lucene.util.fst.FST.<init>(FST.java:308)
    at org.apache.lucene.search.suggest.analyzing.AnalyzingSuggester.load(AnalyzingSuggester.java:593)
    at cc.search.suggestion.SuggestionHandler.loadFileNameSuggester(SuggestionHandler.java:120)
    at cc.search.suggestion.SuggestionHandler.loadDatabases(SuggestionHandler.java:47)
    at cc.search.service.app.service.SearchHandler.<init>(SearchHandler.java:156)
    at cc.search.service.app.service.ServiceApp.<init>(ServiceApp.java:30)
    at cc.search.service.app.service.ServiceApp.main(ServiceApp.java:51)
```

Instead of this, if we can, at the start of the server, it should be inspected if search parsing was actually done (perhaps even maintain a list of parsers that were run when creating a workspace's contents?) and provide a more graceful message (WARNING: Search service enabled but the project was parsed without search - suggestions won't work.) or just shut up about it.

I'd prefer the first option, simply being silent and losing a big chunk of the functionality will derail users.

(cc @nalevi)

**Comment by mcserep** [comment]
The reported bug is more likely to be related with the issue about the not working suggestion database, see #25 .
