### ISSUE TITLE
wildcard * in search does not work

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCompass#345]
![compass](https://user-images.githubusercontent.com/8030953/64945863-d94b3700-d871-11e9-80f1-2c27c497ed50.JPG)

**Comment by mcserep** [comment]
Including a wildcard in the query string results in a Java exception in the *search service*:
```
[WARNING] Getting result failed!
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/lucene/index/memory/MemoryIndex
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at cc.search.service.app.SearchAppCommon.computeResultEntries(SearchAppCommon.java:321)
	at cc.search.service.app.service.SearchHandler.runSearch(SearchHandler.java:131)
	at cc.search.service.app.service.SearchHandler.search(SearchHandler.java:189)
	at cc.search.service.app.service.ServiceApp.search(ServiceApp.java:14)
	at cc.service.search.SearchService$Processor$search.getResult(SearchService.java:416)
	at cc.service.search.SearchService$Processor$search.getResult(SearchService.java:395)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at cc.search.common.ipc.IPCProcessor.serve(IPCProcessor.java:90)
	at cc.search.service.app.service.ServiceApp.main(ServiceApp.java:57)
Caused by: java.lang.NoClassDefFoundError: org/apache/lucene/index/memory/MemoryIndex
	at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.getLeafContext(WeightedSpanTermExtractor.java:359)
	at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extract(WeightedSpanTermExtractor.java:216)
	at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.getWeightedSpanTermsWithScores(WeightedSpanTermExtractor.java:509)
	at org.apache.lucene.search.highlight.QueryScorer.initExtractor(QueryScorer.java:220)
	at org.apache.lucene.search.highlight.QueryScorer.init(QueryScorer.java:186)
	at cc.search.match.matcher.OffsetBasedLineMatcher.<init>(OffsetBasedLineMatcher.java:68)
	at cc.search.match.matcher.OffsetBasedLineMatcher.fromTermVectorField(OffsetBasedLineMatcher.java:179)
	at cc.search.match.matcher.SourceLineMatcherFactory.create(SourceLineMatcherFactory.java:19)
	at cc.search.match.matcher.MasterMatcherFactory.create(MasterMatcherFactory.java:84)
	at cc.search.service.app.SearchAppCommon$SearchResultMatcherTask.call(SearchAppCommon.java:121)
	at cc.search.service.app.SearchAppCommon$SearchResultMatcherTask.call(SearchAppCommon.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Exception in thrown in line 321:
https://github.com/Ericsson/CodeCompass/blob/ff4b4cf72998b1032aed6301f9b8f2ab7cbc3933/plugins/search/service/search-java/src/cc/search/service/app/SearchAppCommon.java#L306-L331

**Comment by mcserep** [comment]
According to the error message, the definition for the class `org/apache/lucene/index/memory/MemoryIndex` is not found. Based on the Lucene documentation, this is located in the `lucene-memory-<version>.jar` file, which is not included in the CodeCompass project (yet!) Will try to add it later and check whether it solves it.
