### ISSUE TITLE
SEGFAULT at the exit of parser binary on Ubuntu 20.04

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#405]
> :warning: **NOTE:** This is after applying #398.

When testing the aforementioned patch, the `SEGFAULT` that seemed to appear in Travis since #393 have found their way into the docker-

I have started the container as described [in the docs](https://github.com/Ericsson/CodeCompass/tree/master/docker#how-to-parse-a-project), but with changed mode:

    cd ~/Work/CodeCompass
    docker run --rm -ti \
      --env DATABASE=sqlite --env BUILD_TYPE=RelWithDebInfo \
      --volume $(readlink -f .):/CodeCompass \
      --volume $(readlink -f CodeCompass):/projects/myproject \
      -p 8001:8080 \
      codecompass:dev \
      /bin/bash

The `SEGFAULT` does **NOT** happen on `Debug` builds.

It happens on `Release` (and `RelWithDebInfo`), irrespective of the `-j` argument to the parser. So it's not a multithreading yadda.

Trying to parse CodeCompass itself (on the branch `bruntib:docker_ubuntu20`, **inside** the container):

    CodeCompass_parser -d "sqlite:database=/CodeCompass/workspace/myproject/data.sqlite" -w /CodeCompass/workspace -n CodeCompass -i /CodeCompass/CodeCompass -i /CodeCompass/build/compile_commands.json

Thanks to `RelWithDebInfo` (and manually installing `gdb` into the image), I've
got a trace:

~~~~
[INFO] Creating indexes from file /CodeCompass/install/share/codecompass/sql/statistics-odb.sql
[INFO] Creating indexes from file /CodeCompass/install/share/codecompass/sql/cpptypedef-odb.sql

Program received signal SIGSEGV, Segmentation fault.
0x000055df7d13c42e in boost::any::~any (this=0x55df7e067d90, __in_chrg=<optimized out>) at /usr/include/boost/any.hpp:79
79                  delete content;

(gdb) bt
#0  0x000055df7d13c42e in boost::any::~any (this=0x55df7e067d90, __in_chrg=<optimized out>) at /usr/include/boost/any.hpp:79
#1  boost::program_options::variable_value::~variable_value (this=0x55df7e067d90, __in_chrg=<optimized out>) at /usr/include/boost/program_options/variables_map.hpp:58
#2  std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value>::~pair (this=0x55df7e067d70,
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_pair.h:208
#3  __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> > (this=0x7ffc4fc03550,
    __p=0x55df7e067d70) at /usr/include/c++/9/ext/new_allocator.h:153
#4  std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> > > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> > (__a=...,
    __p=0x55df7e067d70) at /usr/include/c++/9/bits/alloc_traits.h:497
#5  std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> > >::_M_destroy_node (this=0x7ffc4fc03550, __p=0x55df7e067d50) at /usr/include/c++/9/bits/stl_tree.h:642
#6  std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> > >::_M_drop_node (this=0x7ffc4fc03550, __p=0x55df7e067d50) at /usr/include/c++/9/bits/stl_tree.h:650
#7  std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, boost::program_options::variable_value> > >::_M_erase (this=0x7ffc4fc03550, __x=0x55df7e067d50) at /usr/include/c++/9/bits/stl_tree.h:1915
#8  0x000055df7d11b64a in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/9/ostream:108
~~~~

However, it is not terribly useful...

The issue does **NOT** happen on `Debug` builds, or on Ubuntu **18.04**, but also seems not to corrupt the database.

**Comment by mcserep** [comment]
Fixed by #490.
