### ISSUE TITLE
After following installation and parsing guide I got a blank page when accessing the web server

### ISSUE THREAD

**Issue by codeorcode** [Ericsson/CodeCompass#8]
This might not be an issue but a misconfiguration on my part. I've followed all instructions, and I've also tried the ones from `lazy dog` page but all I get is a blank page and the following debug info in Safari:

http://i.imgur.com/Eyc39OF.png

Here is what I did (after installing required packages and succesfully building codecompass):

# start postgresql
/home/john/cc/CodeCompass-deps/bin/postgres -D /home/john/pgsql_data -p 6250 >pgsql_log 2>&1

# parse the project
CodeCompass parse -f -w /home/john/cc/workdir -n tinyxml -b "g++ *.cpp -std=c++11" --dbuser john --dbport 6250

# start web server
CodeCompass server -w /home/john/cc/workdir -p 6251 --dbport 6250 --dbuser john

No errors are issues on any of those commands.

Thanks for your help and for fixing previous issue, now building of the project went ok.

Here is more info:

INFO CodeCompass: Webserver: [tid: 140659779868480, time: 1477215622] util/src/environment.cpp:143
Detected CodeCompass install path: /home/jonh/cc/CodeCompass-install

Workspace
  id = simple_project
  connection = pgsql:host=localhost;database=simple_project;user=jonh;port=6250
  description = simple_project
  datadir = /home/jonh/cc/workdir/simple_project/data

Workspace
  id = tinyxml
  connection = pgsql:host=localhost;database=tinyxml;user=jonh;port=6250
  description = tinyxml
  datadir = /home/jonh/cc/workdir/tinyxml/data

DEBUG CodeCompass: Webserver: [tid: 140659779868480, time: 1477215622] webserver/pluginable-webserver/src/userstat.cpp:126
The default root interface is: enp0s3
Mongoose web server v. 5.4, starting on port(s) 6251 with web root [/home/jonh/cc/CodeCompass-install/share/codecompass/html]
Oct 23, 2016 12:40:22 PM cc.search.service.app.service.ServiceApp main
INFO: Search server started!
Oct 23, 2016 12:40:22 PM cc.search.service.app.service.ServiceApp main
INFO: Search server started!
Oct 23, 2016 12:40:22 PM cc.search.suggestion.SuggestionHandler loadDatabases
SEVERE: Failed to load the file name suggestion database!
java.io.EOFException
	at org.apache.lucene.store.InputStreamDataInput.readByte(InputStreamDataInput.java:37)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:96)
	at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:134)
	at org.apache.lucene.util.fst.FST.<init>(FST.java:322)
	at org.apache.lucene.util.fst.FST.<init>(FST.java:308)
	at org.apache.lucene.search.suggest.analyzing.AnalyzingSuggester.load(AnalyzingSuggester.java:593)
	at cc.search.suggestion.SuggestionHandler.loadFileNameSuggester(SuggestionHandler.java:120)
	at cc.search.suggestion.SuggestionHandler.loadDatabases(SuggestionHandler.java:47)
	at cc.search.service.app.service.SearchHandler.<init>(SearchHandler.java:158)
	at cc.search.service.app.service.ServiceApp.<init>(ServiceApp.java:30)
	at cc.search.service.app.service.ServiceApp.main(ServiceApp.java:51)

Oct 23, 2016 12:40:22 PM cc.search.suggestion.SuggestionHandler loadDatabases
SEVERE: Failed to load the file name suggestion database!
java.io.EOFException
	at org.apache.lucene.store.InputStreamDataInput.readByte(InputStreamDataInput.java:37)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:96)
	at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:134)
	at org.apache.lucene.util.fst.FST.<init>(FST.java:322)
	at org.apache.lucene.util.fst.FST.<init>(FST.java:308)
	at org.apache.lucene.search.suggest.analyzing.AnalyzingSuggester.load(AnalyzingSuggester.java:593)
	at cc.search.suggestion.SuggestionHandler.loadFileNameSuggester(SuggestionHandler.java:120)
	at cc.search.suggestion.SuggestionHandler.loadDatabases(SuggestionHandler.java:47)
	at cc.search.service.app.service.SearchHandler.<init>(SearchHandler.java:158)
	at cc.search.service.app.service.ServiceApp.<init>(ServiceApp.java:30)
	at cc.search.service.app.service.ServiceApp.main(ServiceApp.java:51)

Oct 23, 2016 12:40:22 PM cc.search.service.app.service.ServiceApp main
INFO: Start serving search for index /home/jonh/cc/workdir/simple_project/data/search
Oct 23, 2016 12:40:22 PM cc.search.service.app.service.ServiceApp main
INFO: Start serving search for index /home/jonh/cc/workdir/tinyxml/data/search

**Comment by whisperity** [comment]
You run the parse commands as `john` on your username, but the logs show `jonh`:

> INFO CodeCompass: Webserver: [tid: 140659779868480, time: 1477215622] util/src/environment.cpp:143
> Detected CodeCompass install path: /home/jonh/cc/CodeCompass-install
> 
> Workspace
> id = simple_project
> connection = pgsql:host=localhost;database=simple_project;user=jonh;port=6250
> description = simple_project
> datadir = /home/jonh/cc/workdir/simple_project/data
> 
> Workspace
> id = tinyxml
> connection = pgsql:host=localhost;database=tinyxml;user=jonh;port=6250
> description = tinyxml
> datadir = /home/jonh/cc/workdir/tinyxml/data

Did you accidentally made a type while installing, or

**Comment by codeorcode** [comment]
It was with other user, I've tried on two configurations with different users but the data I've copied was from both users, so I've change the name by mistake when I've pasted here. I've re-configured all on a new virtual machine and the same thing is happening (blank page). I'll look more into my issue and if I more info I'll post it here. Thank you!

**Comment by csordasmarton** [comment]
I have fixed the problem. It was a missing javascript module which we removed. Please try it again. Now it should work.

**Comment by codeorcode** [comment]
Thank you very much, it is working now!
